# Generated by Django 4.2 on 2025-10-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeupdaterequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
